### ISSUE TITLE
USB webcam alternatives

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#116]
Current body of the USB Camera module text at tessel.io/modules is very minimal. It doesn't note that it should be a UVC-compatible camera, which might cause issues for users seeking alternatives to the Amazon link we provide (e.g. that camera doesn't ship to India).

Current:
![screen shot 2017-07-03 at 11 39 20 am](https://user-images.githubusercontent.com/454690/27804532-481f2690-5fe4-11e7-8157-5fe6c739827b.png)

The text should include a note that the camera should be UVC-compatible and possibly link to this Linux community-maintained list: http://www.ideasonboard.org/uvc/

**Comment by andy5995** [comment]
I looked at the web page, but couldn't find the matching info in tessel.io/views/modules.jade

Did I miss something?

**Comment by Frijol** [comment]
Good question @andy5995! I believe it pulls from https://github.com/tessel/hardware-modules/blob/master/modules.json (which ideally we'd transition to the website repo per https://github.com/tessel/hardware-modules/issues/14)

**Comment by andy5995** [comment]
I noticed the code is showing on the [web page](https://tessel.io/modules#tessel-av):

`Should be <a title='Linux UVC driver and tools' href='http://www.ideasonboard.org/uvc/'>UVC-compatible</a>,`

I've examined it and don't see a problem. The only difference between that link and the other links on the page is my addition of the _title_ attribute.

I'll fix this...  if you tell me what the problem is! ;)

**Comment by Frijol** [comment]
oh, hm, good catch..

**Comment by Frijol** [comment]
Thanks for https://github.com/tessel/tessel.io/pull/118! Unfortunately it doesn't fix the showing code :/. I've created https://github.com/tessel/tessel.io/issues/119 so we don't forget to look into that.
